events { worker_connections 1024; }

http {
    server {
        listen 80;
        server_name localhost;

        # Auth Service
        location /authh/ {
            proxy_pass http://tb-auth-service:4001/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Assessment Service (jisme Judge0 connected hai)
        location /assessmentt/ {
            proxy_pass http://tb-assessment-service:4005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
         location /userr/ {
            proxy_pass http://tb-user-service:4002/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
         location /coursess/ {
            proxy_pass http://tb-course-service:4004/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
         location /adminn/ {
            proxy_pass http://tb-admin-service:4003/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
         
        
        
    }
}

